-- 프로젝트에 ojdbc8.jar 연결 후에 진행한다.
-- 	1. 프로젝트 우 클릭 -> 빌드 패스 - 콘피그빌드패스 -> 라이브러리 탭에 가서  classPath 누르고 ojdbc8.jar 연결
--	2. deployment assembly 가서 java build path -> ojdbc8.jar 추가 -> apply
-- 	3. 결과 -> Referenced Libraies에 ojdbc8.jar 보이면 성공 !